Adding container for building LaTeX
OpenCyphal/docker_toolchains pull request #3
Opened 2020-02-29 05:58 UTC by thirtytwobits

I give you; the texer!

2020-02-29 11:23 UTC, pavel-kirienko requested changes
Eh no. Won't work.

We need pdfTeX version 3.14159265-2.6-1.40.16. If you just pull the latest from the Ubuntu repos, you get a newer one that produces bad documents. The worst thing is that the build doesn't fail and if you just look at the front page or something you won't notice the problem.

We should update our [document class definition](https://github.com/UAVCAN/specification/blob/master/specification/uavcandoc.cls) to be compatible with the newer releases, but it's not a long-term solution either because when the next release comes around our style will get broken again. Maybe we could just freeze a specific version and avoid touching anything because the thing is incredibly fragile.

2020-03-01 05:35 UTC, thirtytwobits commented
> Eh no. Won't work.
> 
> We need pdfTeX version 3.14159265-2.6-1.40.16. If you just pull the latest from the Ubuntu repos, you get a newer one that produces bad documents. The worst thing is that the build doesn't fail and if you just look at the front page or something you won't notice the problem.
> 
> We should update our [document class definition](https://github.com/UAVCAN/specification/blob/master/specification/uavcandoc.cls) to be compatible with the newer releases, but it's not a long-term solution either because when the next release comes around our style will get broken again. Maybe we could just freeze a specific version and avoid touching anything because the thing is incredibly fragile.

So, I just followed the readme:

```
In order to compile the document, install TexLive (Debian-based APT packages: `texlive-full lyx`)
```

Do you happen to know what version of texlive-full is the correct one?

2020-03-02 10:29 UTC, pavel-kirienko approved these changes

2020-03-02 10:30 UTC, pavel-kirienko commented on texer/Dockerfile
> +# Builds the c_cpp/ubuntu-18.04 toolchain container.
The comment is wrong

2020-03-02 22:11 UTC, merged